### ISSUE TITLE
Can you add Protector Redo mod support?

### ISSUE THREAD

**Issue by amadin** [HybridDog/connected_chests#2]
http://github.com/tenplus1/protector

**Comment by HybridDog** [comment]
What do you mean by support for that mod?

**Comment by amadin** [comment]
I mean support for Protected chest.

**Comment by HybridDog** [comment]
Ok, it should be possible.

**Comment by HybridDog** [comment]
Sorry, l don't add support for more chests because l'd need to rewrite almost the whole mod for decent results, see https://github.com/HybridDog/connected_chests/commit/482de1c06b7a77b0449e0131119ac681a27c5fe3.

**Comment by amadin** [comment]
Sorry, this mod is almost on all servers.

**Comment by HybridDog** [comment]
amadin, l restructured the mod, the PR is there:
 https://github.com/tenplus1/protector/pull/18
